version: "3.9"
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql:/etc/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
  redis:
    image: redis:7.0.4
    container_name: redis
    volumes:
      - ./data/redis:/data
    restart: always
  webhook:
    build: ./dockerfiles/webhook
    container_name: webhook
    volumes:
      - ./conf/webhook/.ssh:/root/.ssh
      - ./www:/home
      - ./sh/webhook/:/sh
    tty: true
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sh:/sh
      - ./www:/home
      - ./conf/nginx/conf:/etc/nginx/conf.d
      - ./conf/nginx/cert:/etc/nginx/cert
    command:
      - /bin/bash
      - -c
      - |
        chmod +x -R /sh
        /sh/wait-for-it.sh webhook:9000 -- nginx -g 'daemon off;'
    restart: always
