version: "3.7"
services:
  blog:
    image: blog
    build: ./git
    working_dir: /home
    tty: true
    ports:
      - 1313:1313
    volumes:
      - ./www:/home
    command: 
      - /bin/bash
      - -c
      - |
        rm -rf /home/blog
        cd /home
        git clone git://github.com/Chance-fyi/blog.git
        cd /home/blog
        hugo server
  nginx:
    image: nginx
    working_dir: /home
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/home
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert